server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /v1/ {
        proxy_pass http://pii-module-v2:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Admin-Key $http_x_admin_key;
    }

    location /process {
        proxy_pass http://pii-module-v2:8080;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri /index.html;
    }
}